const TestimonialApi = [
  {
    id: 1,
    image: "https://source.unsplash.com/600x400/?men",
    place: "Mumbai",
    name: "Alex Costa",
    user: "Verified User",
    keyword: "Service was Exceptional!!",
    date: "Mar 4, 2020 - Mar 12, 2020",
    desc: "“The service at the Hotel Monteleone was exceptional. There was absolutely no issue that was not addressed timely and with satisfactory results.We were particulary impressed with how the hotel staff anticipated our needs (periodically coming by the Board Room to check with us).”",
  },
  {
    id: 2,
    image: "https://source.unsplash.com/600x400/?girl",
    // image: "./image/slide2.png",
    place: "Punjab",
    name: "Jaspreet Kaur",
    user: "Verified User",
    keyword: "Amazing Food",
    date: "Jan 4, 2015 - Jan 8, 2015",
    desc: "“Everyone loved the hotel and the food. Sam and Dan were very impressed in what a very well oiled machine you run!”",
  },
  {
    id: 3,
    image: "https://source.unsplash.com/600x400/?boy-face",
    place: "Delhi",
    name: "Krunal Verma",
    user: "Verified User",
    keyword: "Excellence Service",
    date: "July 4, 2021 - July 5, 2021",
    desc: "“Where do I start, I was so pleased with the meeting location and space and wanted to say thank you. The hospitality in this hotel has been nothing short of “Service Excellence” The rooms are spacious, clean and super comfortable.”",
  },
  {
    id: 4,
    image: "https://source.unsplash.com/600x400/?hotgirl",
    place: "Goa",
    name: "Jennifer Dsousa",
    user: "Verified User",
    keyword: "Nice Service",
    date: "Aug 28, 2019 - Aug 30, 2019",
    desc: "“Thank you again for everything. The meeting went very well. Everyone loved the hotel and the support all your staff provided. It was a pleasure to work with a true professional like yourself. You made everything run seamless.”",
  },
  {
    id: 5,
    image: "https://source.unsplash.com/600x400/?girl-face",
    place: "Chennai",
    name: "Ankita Chettiar",
    user: "Verified User",
    keyword: "Great Support.",
    date: "May 12, 2019",
    desc: "“Got great support with the Technical team related to my refund and Cancellation of Hotel.”",
  },
]

export default TestimonialApi
